enyo.depends(
	"source/MainView.js",
    "source/OptionView.js",
    "source/DistrictSelectionView.js",
    "source/StationListView.js",
    "source/StationListItem.js",
    "source/ErrorDialog.js",
	"source/MainView.css"
);