enyo.depends(
	"source/MainView.js",
    "source/OptionView.js",
    "source/DistrictSelectionView.js",
    "source/StationListView.js",
    "source/StationListItem.js",
    "source/ErrorDialog.js",
    "source/ConnectionView.js",
    "source/StationDetailView.js",
    "source/GPSSearchView.js",
    "source/AddressSearchView.js",
	"css/MainView.css"
);